from .details_screen import details_screen
from .start_screen import start_screen
from .student_modify_screen import student_modify_screen
from .students_screen import students_screen
from .insertstudent_screen import insertstudent_screen
from .mess_screen import mess_screen
from .visitor_screen import visitor_screen
from .studentsview_screen import studentsview_screen
from .insertvisitor_screen import insertvisitor_screen
from .yearselect_screen import yearselect_screen
from .roomview_screen import roomview_screen,yeardata
from .canteenview_screen import canteenview_screen
from .insertcanteen_screen import insertcanteen_screen
from .student_delete_screen import student_delete_screen
